### ISSUE TITLE
Wrong Link

### ISSUE THREAD

**Issue by chaaklau** [gwinterstein/Cifu#1]
This link the paper is incorrect.
`Available here: http://www.lrec-conf.org/proceedings/lrec2020/pdf/2020.lrec-1.374.pdf`

The correct link should be:
http://www.lrec-conf.org/proceedings/lrec2020/pdf/2020.lrec-1.375.pdf

**Comment by gwinterstein** [comment]
First of all: Hi.

Thanks for pointing the erroneous link.

Best,

gW
